### PR TITLE
Don't build pushes from non-org repos.

### PR DESCRIPTION
**Pull request by dschaper**

### CODE REVIEW

**Comment by dschaper** [comment]
This can merge to master or to a new branch called latest if that makes more sense. Will need to make sure the `latest` tag points to the right commit after merge.

**Comment by dschaper** [comment]
Conditionals are being seen but I think I have the wrong conditions.
Annotation 2020-07-30 130917


Trying to build all PR's and then any push that is from our repo. Not sure if that means don't build forks, or why my current regex isn't working.

**Comment by dschaper** [comment]
Oh, `head_repo` only works for `pull_request`, has no function for `push.`

**Comment by dschaper** [comment]
Commit 4ad4ed2 is tagged as `latest` and drafted as pre-release

**Comment by dschaper** [comment]
Fat finger, did not mean to close.

**Review by PromoFaux — APPROVED** [review]

**Comment by dschaper** [comment]
This is already tagged as `latest` so the travis builds should already be using it.

**Pull request merged**
